### ISSUE TITLE
MENMA: after 64 bit patch, too many errors, toolbox won't work, see pic

### ISSUE THREAD

**Issue by lidel97** [tera-private-toolbox/tera-toolbox#2]
![toolbox error](https://user-images.githubusercontent.com/35901666/178056254-c6795900-87a1-4720-b286-3c79b83ae8c7.jpg)

**Comment by justkeepquiet** [comment]
At the moment the **Auto-Guildquest** module is not supported in patch 100. You need to disable it and wait for updates.

**Comment by justkeepquiet** [comment]
Opcodes has been updated. Please restart toolbox and check.
