### ISSUE TITLE
Duplicated opcodes in protocol ver. 376012

### ISSUE THREAD

**Issue by foglio1024** [tera-private-toolbox/tera-toolbox#3]
https://github.com/tera-private-toolbox/tera-toolbox/blob/master/data/data.json#L4564
https://github.com/tera-private-toolbox/tera-toolbox/blob/master/data/data.json#L4473

I suggest to change or delete `C_CHANGE_EQUIP_PRESET`, considering `C_GACHA_CANCEL`  is correctly mapped to `59172` in Menma's TERA proxy (no idea about Asura's, their integrated toolbox doesn't have them mapped at all).

**Comment by foglio1024** [comment]
Actually this is the full list of duplicated opcodes for protocol 376012:

```tsv
C_CHANGE_EQUIP_PRESET	C_GACHA_CANCEL	59172
C_UNMOUNT_VEHICLE	S_START_DRIVE_AIRSHIP	30035
S_BATTLE_FIELD_ENTRANCE_INFO	S_BATTLE_FIELD_STRONGHOLD_STATE	37935
S_CHANGE_PARTY_MANAGER	S_NEW_GOLD_RACE_INFO	22421
S_CHANGE_PARTY_MEMBER_AUTHORITY	S_VIEW_PARTY_INVITE	52162
S_CURR_FLY_MOVE_INFO	S_DEAD_LOCATION	36540
S_DISTRIBUTOR_DATA	S_RESULT_BIDDING_DICE_THROW	45185
S_GET_USER_GUILD_LOGO	S_SEND_VIP_SYSTEM_INFO	32250
S_ITEM_CUSTOM_STRING	SU_NEW_IM_2	57742
S_LEAVE_PARTY	S_PARTY_LOOTING_METHOD	39566
S_LOADING_SCREEN_CONTROL_INFO	S_REQUEST_UPDATE_CUSTOM_USER_CUSTOMIZING	50568
S_UNICAST_TRANSFORM_DATA	S_USER_AIM	44789
SU_CHANGE_EP_PAGE	TTB_S_LOAD_EP_PAGE	39208
```

**Comment by justkeepquiet** [comment]
Solved. Thank you for your contribution.
