### ISSUE TITLE
Unicast

### ISSUE THREAD

**Issue by bl0nde** [tera-private-toolbox/tera-toolbox#4]
Hello, I am not sure if this is planning on being worked on or not but my unicast does not display properly. I only see a blank window come up when I press the hotkeys to open unicast.
Image: https://i.postimg.cc/52yZMCGY/Unicast.png
Thank you. <3

**Comment by justkeepquiet** [comment]
Hi. This unicast not supported by patch 100.

**Comment by justkeepquiet** [comment]
In the near future I will publish a compatible version for patch 100.

**Comment by justkeepquiet** [comment]
Unicast Offline for patch 100 has been added.
Check **Get More Mods** tab. Вкладка "Скачать модули".
