### ISSUE TITLE
Self-update error

### ISSUE THREAD

**Issue by Aki62** [tera-private-toolbox/tera-toolbox#5]
File hash mismatch in downloaded file "bin/update-self.js"

[update] Self-update started (Branch: master)
[update] - Error downloading bin/update-self.js: file hash mismatch (expected: 1E1E98CE62B8D00DFEB01313EE109C17CBEB8F65A74F44190C4AD9EB368D8450, found: AA52A0EB27AB7A0334C585C3F70A127DD3FFA9A2AA1D7CED9E6666F9DC41D225)!
[update] Self-update failed
[update] ERROR: Unable to perform self-update!
[update] ERROR: Please join https://discord.gg/659YbNY and check the #info, #toolbox-faq, and #help channels for further instructions.

**Comment by justkeepquiet** [comment]
All hashes in the repository correspond to files. However, the Github raw cache still contain files from older commits. We have contacted the Github support, but there is no information yet on when the problem will be solved. You can only wait.

**Comment by justkeepquiet** [comment]
As long as the problem persists, you can use the fallback repository and update your Toolbox using the link: https://gitlab.com/tera-private-toolbox/tera-toolbox/-/archive/master/tera-toolbox-master.zip

If you don't want to update the entire toolbox, you can simply download file **[update-self.js](https://gitlab.com/tera-private-toolbox/tera-toolbox/-/raw/master/bin/update-self.js?inline=false)** and place it in the **bin** folder of your Toolbox, overwriting the existing file. After that, all updates should install correctly.
