### ISSUE TITLE
Toolbox works correctly, but i'm getting the relog screen every now and then - Menma

### ISSUE THREAD

**Issue by Reny900** [tera-private-toolbox/tera-toolbox#6]
Not sure what is causing this, there is actually no error in the toolbox log,
![image](https://user-images.githubusercontent.com/19189602/218297201-19483c6e-2642-41ac-8b08-71715890420f.png)

just by standing still i get prompted this, and, because it tested it, changing channel while this is on screen doesnt actually do anything since you do change channel, but get to the relog screen anyway

**Comment by justkeepquiet** [comment]
Check which modules you are using, you may have installed some module that is causing this issue. We recommend using a clean toolbox (without any questionable modules and cheats) for testing purposes. If the problem persists, go to Menma discord for support.

**Comment by Reny900** [comment]
ended up taking the clean toolbox with the same module i was using before, but had the same self-update issue. Replacing the file as per Issue #5 worked fine, and the problem didnt repeat itself. 
Thanks anyway, i forgot to update this
