### ISSUE TITLE
GPK mods cant be loaded anymore (Menma's Tera)

### ISSUE THREAD

**Issue by Yasukii** [tera-private-toolbox/tera-toolbox#7]
After todays maintemamce on Menmas tera, GPK mods  cant be loaded and applied anymore.

This is the error that toolbox logs: 

![electron_fHrgV1y2Fo](https://user-images.githubusercontent.com/34219032/230652023-e0dd8450-de50-4b6a-b6f6-b7f916a99980.png)

**Comment by justkeepquiet** [comment]
Hi. This issue is not related to the Toolbox. You need to contact the author of the GPK mod (I think you mean [TCC](https://github.com/Foglio1024/tcc-toolbox-release/)), or find out about the problem on the Menma's TERA discord.
