### ISSUE TITLE
Error S_Login since 2.1 (Menmas)

### ISSUE THREAD

**Issue by Yasukii** [tera-private-toolbox/tera-toolbox#8]
![electron_Ck6rMmLdWa](https://github.com/tera-private-toolbox/tera-toolbox/assets/34219032/ab5c8092-686e-4be5-8809-9ecfc583bb4b)

**Comment by justkeepquiet** [comment]
Hi,
This issue is related to the module you are using. It is not related to any problems in not the tera-game-state or TeraToolbox.
Remove or fix your modules that use the tera-game-state module.

For help, you can join our discord: https://discord.gg/CZMYNhXwwS
